import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import LuyenTap from '../components/LuyenTap'
import DeThi from '../components/DeThi'
import LoiIch from '../components/LoiIch'
import NenTang from '../components/NenTang'
import DangKy from '../components/DangKy'
import Blog from '../components/Blog'
import Footer from '../components/Footer'
import DanhGia from '../components/DanhGia'
import Navbar from '../components/Navbar'




export default function Home() {
  return (
    <>
      <Head>
        <title>Hocthongminh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Navbar/>
        <Banner/>
        <LuyenTap/>
        {/* <DeThi2/> */}
        <DeThi/>
        <LoiIch/>
        <NenTang/>
        <DangKy/>
        <DanhGia/>
        <Blog/>
        <Footer/>
      </main>
    </>
  )
}
